/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.venta;

import control.basededatos.BaseDatosVirtual;
import control.venta.OperacionesVenta;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.TablaDetalleViewModel;
import modelo.VentaModelo;
import util.ImprimirTicket;

/**
 *
 * @author luiscobian
 */
public class Venta extends javax.swing.JDialog {

    private List<TablaDetalleViewModel> detalle; 
    private BaseDatosVirtual bd; 
    private int folio; 
    private double total;
    
    /**
     * Creates new form Venta
     */
    public Venta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jlFecha.setText(getFecha());
        detalle = new ArrayList<>();
        actualizarVenta(); 
        bd = new BaseDatosVirtual();
        folio = bd.numeroVentas() + 1;
        String folio = String.format("%03d",
                                this.folio);
        jlTicket.setText(folio);
    }
    
    private void actualizarVenta() {
        /// actualizacion 
        String[] columns = {"Cant", "Descripción"
                            , "Precio", "Total", "Codigo"};
        String[][] datos = extraerDatos(); 
        DefaultTableModel model = new 
            DefaultTableModel(datos, 
                    columns); 
        jtDetalle.setModel(model);
        jtDetalle.removeColumn(jtDetalle.getColumnModel().getColumn(4));
    }
    
    private String[][] extraerDatos(){
        String[][] datos = new String
                  [detalle.size()][5]; 
        int i=0; 
        double totalVenta = 0; 
        for(TablaDetalleViewModel elem : detalle){
            datos[i][0] = "" + elem.getCantidad();
            datos[i][1] = elem.getDescripcion(); 
            datos[i][2] = String.format
                        ("%.2f",
                           elem.getPrecio());
            datos[i][3] = String.format
                        ("%.2f",
                           elem.getTotal());
            datos[i][4] = elem.getCodigo();
            i++;
            totalVenta +=elem.getTotal(); 
        }
        jlTotal.setText(String.format
                      ("$ %.2f", totalVenta));
        total = totalVenta;
        return datos; 
    }
    
    private String getFecha() {
        Calendar calendar = Calendar.getInstance();
        Locale locale = 
                new Locale("es", "MX");
        SimpleDateFormat sdf = 
             new SimpleDateFormat("dd-MMMM-yyyy"
                , locale);
        return sdf.format(calendar.getTime());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlTicket = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDetalle = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Venta al publico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel2.setText("Ticket: #");

        jlTicket.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jlTicket.setText("001");

        jlFecha.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jlFecha.setText("01-feb-2023");

        jtBuscar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("jButton1");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jtDetalle.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jtDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtDetalle);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel5.setText("TOTAL A PAGAR");

        jlTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jlTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTotal.setText("$100.00");

        btnRegistrar.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBorrar.setText("borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jButton3.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlTicket)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnBorrar)
                            .addComponent(jButton3))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlTicket)
                    .addComponent(jlFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlTotal)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBuscarActionPerformed
        // TODO add your handling code here:
        hacerBusqueda(); 
    }//GEN-LAST:event_jtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        hacerBusqueda();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int renglonSeleccionado = jtDetalle.getSelectedRow();         
        if(renglonSeleccionado>=0){
            String codigo = jtDetalle.getModel().getValueAt
             (renglonSeleccionado, 4).toString(); 
            var res = OperacionesVenta.borrar(detalle, codigo); 
            if(res) actualizarVenta();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        VentaModelo venta = new VentaModelo();
        venta.setFolio("" + folio);
        venta.setFecha(Calendar.getInstance().getTime());
        venta.setTotal(total);
        venta.setDetalle(detalle);
        
        if(bd.guardarVenta(venta)){
            System.out.println("Aqui esta imprimiendo.......");
            ImprimirTicket imprimir = new ImprimirTicket(); 
            imprimir.printTicket(venta);
            // limpiando campos 
            folio ++ ;
            String folio = String.format("%03d", this.folio); 
            jlTicket.setText(folio);
            detalle = new ArrayList<>(); 
            actualizarVenta();
        }else 
        {
            JOptionPane.showMessageDialog(this, 
                    "Ocurrio un error"); 
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    
    private void hacerBusqueda() {
        String codigo = jtBuscar.getText(); 
        Producto productoDato = 
                bd.buscarProductoVenta(codigo);
        if(productoDato!=null){        
            OperacionesVenta.agregar(detalle, productoDato);
            actualizarVenta();
            jtBuscar.setText("");
        } else 
            JOptionPane.showMessageDialog(
                    this,
                    "Producto no existente");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlTicket;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JTextField jtBuscar;
    private javax.swing.JTable jtDetalle;
    // End of variables declaration//GEN-END:variables
}
